/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Relation#getFromEntity <em>From Entity</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Relation#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Relation#getToEntity <em>To Entity</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Relation#getCardinality <em>Cardinality</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Relation#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation()
 * @model
 * @generated
 */
public interface Relation extends EObject
{
  /**
   * Returns the value of the '<em><b>From Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Entity</em>' reference.
   * @see #setFromEntity(Entity)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation_FromEntity()
   * @model
   * @generated
   */
  Entity getFromEntity();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Relation#getFromEntity <em>From Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Entity</em>' reference.
   * @see #getFromEntity()
   * @generated
   */
  void setFromEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Relation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>To Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Entity</em>' reference.
   * @see #setToEntity(Entity)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation_ToEntity()
   * @model
   * @generated
   */
  Entity getToEntity();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Relation#getToEntity <em>To Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Entity</em>' reference.
   * @see #getToEntity()
   * @generated
   */
  void setToEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardinality</em>' attribute.
   * @see #setCardinality(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation_Cardinality()
   * @model
   * @generated
   */
  String getCardinality();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Relation#getCardinality <em>Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cardinality</em>' attribute.
   * @see #getCardinality()
   * @generated
   */
  void setCardinality(String value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRelation_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // Relation
